// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// icc_beta
Rcpp::List icc_beta(const arma::mat& X, const arma::vec& l2id, const arma::mat& T, double vy);
RcppExport SEXP iccbeta_icc_beta(SEXP XSEXP, SEXP l2idSEXP, SEXP TSEXP, SEXP vySEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP );
        Rcpp::traits::input_parameter< const arma::vec& >::type l2id(l2idSEXP );
        Rcpp::traits::input_parameter< const arma::mat& >::type T(TSEXP );
        Rcpp::traits::input_parameter< double >::type vy(vySEXP );
        Rcpp::List __result = icc_beta(X, l2id, T, vy);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
